/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-03-14 20:25:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ucl.ac.uk.notesapp.model.entity.Note;
import ucl.ac.uk.notesapp.model.entity.TextNote;

public final class TextNote_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ucl.ac.uk.notesapp.model.entity.Note");
    _jspx_imports_classes.add("ucl.ac.uk.notesapp.model.entity.TextNote");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>New Note</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/TextNote.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"form-container\">\r\n");
      out.write("    <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${action}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("    <form id=\"noteForm\" action=\"/crud/createNote\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\", name=\"noteType\", value=\"text\">\r\n");
      out.write("        <input type=\"text\" name=\"title\" id=\"noteTitle\" placeholder=\"Input title...\" required>\r\n");
      out.write("        <select name=\"subject\" id=\"noteSubject\">\r\n");
      out.write("            ");
 List<String> subjects = (List<String>) request.getAttribute("subjects");
                for(String subject : subjects) {
      out.write("\r\n");
      out.write("            <option value=\"");
      out.print(subject);
      out.write('"');
      out.write('>');
      out.print( subject );
      out.write("</option>\r\n");
      out.write("            ");
   } 
      out.write("\r\n");
      out.write("        </select>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <br>\r\n");
      out.write("        <input type=\"checkbox\" name=\"tags\" value=\"Star\">Star\r\n");
      out.write("        <input type=\"checkbox\" name=\"tags\" value=\"Urgent\">Urgent\r\n");
      out.write("        <input type=\"checkbox\" name=\"tags\" value=\"Pending\">Pending\r\n");
      out.write("        <input type=\"checkbox\" name=\"tags\" value=\"Review\">Review\r\n");
      out.write("        <input type=\"checkbox\" name=\"tags\" value=\"Idea\">Idea\r\n");
      out.write("        <br>\r\n");
      out.write("        <textarea rows=\"14\" cols=\"42\" name=\"content\" id=\"noteContent\" placeholder=\"Enter...\"></textarea>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <button type=\"button\" id=\"deleteButton\" style=\"display: none\" onclick=\"deleteNote()\">Delete</button>\r\n");
      out.write("    <a href=\"/load/loadNoteList\" class=\"back-link\" id=\"backLink\">Back to All Notes</a>\r\n");
      out.write("    <span class=\"save-notice\" id=\"saveNotice\">Saved!</span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    let noteId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${action}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" === \"edit\" ? \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${note.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" : null;\r\n");
      out.write("    console.log(noteId)\r\n");
      out.write("    window.onload = function() {\r\n");
      out.write("        ");
 if ("edit".equals(request.getAttribute("action"))) {
            Note note = (Note) request.getAttribute("note");
        
      out.write("\r\n");
      out.write("        console.log(\"EDIT\");\r\n");
      out.write("        document.getElementById(\"noteTitle\").value = \"");
      out.print( note.getTitle() );
      out.write("\";\r\n");
      out.write("        document.getElementById(\"noteSubject\").value = \"");
      out.print( note.getSubject() );
      out.write("\";\r\n");
      out.write("        ");
 if (note instanceof TextNote) { 
      out.write("\r\n");
      out.write("        document.getElementById(\"noteContent\").value = \"");
      out.print( ((TextNote) note).getContent() );
      out.write("\";\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 for (String tag : note.getTags()) { 
      out.write("\r\n");
      out.write("        document.querySelector(\"input[name='tags'][value='");
      out.print( tag );
      out.write("']\").checked = true;\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        document.getElementById(\"noteForm\").action = \"/crud/updateNote?id=");
      out.print( note.getId() );
      out.write("\";\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    const form = document.getElementById(\"noteForm\");\r\n");
      out.write("    const titleInput = document.getElementById(\"noteTitle\");\r\n");
      out.write("    const contentInput = document.getElementById(\"noteContent\");\r\n");
      out.write("    const formContainer = document.querySelector(\".form-container\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function saveNote() {\r\n");
      out.write("        const title = titleInput.value.trim();\r\n");
      out.write("        if (!title) {\r\n");
      out.write("            console.log(\"Title is empty, skipping save\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const params = new URLSearchParams();\r\n");
      out.write("        const formData = new FormData(form);\r\n");
      out.write("        params.append(\"title\", formData.get(\"title\"));\r\n");
      out.write("        params.append(\"subject\", formData.get(\"subject\"));\r\n");
      out.write("        params.append(\"content\", formData.get(\"content\"));\r\n");
      out.write("        const tags = formData.getAll(\"tags\");\r\n");
      out.write("        tags.forEach(tag => params.append(\"tags\", tag));\r\n");
      out.write("\r\n");
      out.write("        console.log(\"Saving, noteId:\", noteId);\r\n");
      out.write("        let url = noteId ? \"/crud/updateNote?id=\" + encodeURIComponent(noteId) : \"/crud/createNote\";\r\n");
      out.write("        console.log(url)\r\n");
      out.write("        fetch(url, {\r\n");
      out.write("            method: \"POST\",\r\n");
      out.write("            headers: {\r\n");
      out.write("                \"Content-Type\": \"application/x-www-form-urlencoded\"\r\n");
      out.write("            },\r\n");
      out.write("            body: params.toString()\r\n");
      out.write("        }).then(response => {\r\n");
      out.write("            if (!response.ok) throw new Error(\"Request failed with status: \" + response.status);\r\n");
      out.write("            if (!noteId) {\r\n");
      out.write("                return response.text().then(id => {\r\n");
      out.write("                    noteId = id;\r\n");
      out.write("                    form.action = \"/crud/updateNote?id=\" + id;\r\n");
      out.write("                    console.log(\"Created note with ID:\", noteId);\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }).then(() => {\r\n");
      out.write("            const notice = document.getElementById(\"saveNotice\");\r\n");
      out.write("            notice.classList.add(\"show\");\r\n");
      out.write("            setTimeout(() => notice.classList.remove(\"show\"), 1000);\r\n");
      out.write("        }).catch(err => console.error(\"Save failed:\", err));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function debounce(func, wait) {\r\n");
      out.write("        let timeout;\r\n");
      out.write("        return function() {\r\n");
      out.write("            clearTimeout(timeout);\r\n");
      out.write("            timeout = setTimeout(func, wait);\r\n");
      out.write("        };\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    titleInput.addEventListener(\"blur\", debounce(saveNote, 500));\r\n");
      out.write("    contentInput.addEventListener(\"blur\", debounce(saveNote, 500));\r\n");
      out.write("    formContainer.addEventListener(\"mouseleave\", debounce(saveNote, 500));\r\n");
      out.write("\r\n");
      out.write("    // Save when returning back\r\n");
      out.write("    document.getElementById(\"backLink\").addEventListener(\"click\", function(e) {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        saveNote();\r\n");
      out.write("        setTimeout(() => window.location.href = this.href, 500);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
